INSERT INTO states (code, name, country_code) VALUES ('NY', 'New York', 'US');
INSERT INTO states (code, name, country_code) VALUES ('CA', 'California', 'US');
INSERT INTO states (code, name, country_code) VALUES ('DC', 'District of Columbia', 'US');
INSERT INTO states (code, name, country_code) VALUES ('PA', 'Pennsylvania', 'US');
INSERT INTO states (code, name, country_code) VALUES ('IL', 'Illinois', 'US');
INSERT INTO states (code, name, country_code) VALUES ('LA', 'Louisiana', 'US');
INSERT INTO states (code, name, country_code) VALUES ('MA', 'Massachusetts', 'US');
INSERT INTO states (code, name, country_code) VALUES ('TX', 'Texas', 'US');
INSERT INTO states (code, name, country_code) VALUES ('FL', 'Florida', 'US');
INSERT INTO states (code, name, country_code) VALUES ('WA', 'Washington', 'US');
INSERT INTO states (code, name, country_code) VALUES ('OR', 'Oregon', 'US');
INSERT INTO states (code, name, country_code) VALUES ('CO', 'Colorado', 'US');
INSERT INTO states (code, name, country_code) VALUES ('GA', 'Georgia', 'US');
INSERT INTO states (code, name, country_code) VALUES ('NC', 'North Carolina', 'US');
INSERT INTO states (code, name, country_code) VALUES ('VA', 'Virginia', 'US');
INSERT INTO states (code, name, country_code) VALUES ('MD', 'Maryland', 'US');
INSERT INTO states (code, name, country_code) VALUES ('NJ', 'New Jersey', 'US');
INSERT INTO states (code, name, country_code) VALUES ('CT', 'Connecticut', 'US');
INSERT INTO states (code, name, country_code) VALUES ('VT', 'Vermont', 'US');
INSERT INTO states (code, name, country_code) VALUES ('NH', 'New Hampshire', 'US');
INSERT INTO states (code, name, country_code) VALUES ('ME', 'Maine', 'US');
INSERT INTO states (code, name, country_code) VALUES ('RI', 'Rhode Island', 'US');
INSERT INTO states (code, name, country_code) VALUES ('DE', 'Delaware', 'US');
INSERT INTO states (code, name, country_code) VALUES ('WV', 'West Virginia', 'US');
INSERT INTO states (code, name, country_code) VALUES ('KY', 'Kentucky', 'US');
INSERT INTO states (code, name, country_code) VALUES ('TN', 'Tennessee', 'US');
INSERT INTO states (code, name, country_code) VALUES ('SC', 'South Carolina', 'US');
INSERT INTO states (code, name, country_code) VALUES ('AL', 'Alabama', 'US');
INSERT INTO states (code, name, country_code) VALUES ('MS', 'Mississippi', 'US');
INSERT INTO states (code, name, country_code) VALUES ('AR', 'Arkansas', 'US');
INSERT INTO states (code, name, country_code) VALUES ('OK', 'Oklahoma', 'US');
INSERT INTO states (code, name, country_code) VALUES ('KS', 'Kansas', 'US');
INSERT INTO states (code, name, country_code) VALUES ('NE', 'Nebraska', 'US');
INSERT INTO states (code, name, country_code) VALUES ('SD', 'South Dakota', 'US');
INSERT INTO states (code, name, country_code) VALUES ('ND', 'North Dakota', 'US');
INSERT INTO states (code, name, country_code) VALUES ('MT', 'Montana', 'US');
INSERT INTO states (code, name, country_code) VALUES ('WY', 'Wyoming', 'US');
INSERT INTO states (code, name, country_code) VALUES ('ID', 'Idaho', 'US');
INSERT INTO states (code, name, country_code) VALUES ('UT', 'Utah', 'US');
INSERT INTO states (code, name, country_code) VALUES ('AZ', 'Arizona', 'US');
INSERT INTO states (code, name, country_code) VALUES ('NV', 'Nevada', 'US');
INSERT INTO states (code, name, country_code) VALUES ('NM', 'New Mexico', 'US');
INSERT INTO states (code, name, country_code) VALUES ('AK', 'Alaska', 'US');
INSERT INTO states (code, name, country_code) VALUES ('HI', 'Hawaii', 'US');
INSERT INTO states (code, name, country_code) VALUES ('MO', 'Missouri', 'US');
INSERT INTO states (code, name, country_code) VALUES ('IA', 'Iowa', 'US');
INSERT INTO states (code, name, country_code) VALUES ('MN', 'Minnesota', 'US');
INSERT INTO states (code, name, country_code) VALUES ('WI', 'Wisconsin', 'US');
INSERT INTO states (code, name, country_code) VALUES ('MI', 'Michigan', 'US');
INSERT INTO states (code, name, country_code) VALUES ('IN', 'Indiana', 'US');
INSERT INTO states (code, name, country_code) VALUES ('OH', 'Ohio', 'US');
