-- Simple import without foreign key constraints
DELETE FROM contact_assignments;
DELETE FROM contacts;

INSERT INTO contacts (id,first_name,last_name,email_primary,email_secondary,company,website,company_linkedin,imdb,facebook,instagram,linkedin,wikipedia,biography,priority,seen_film,doc_branch_member,location_country,location_state,location_city,location_state_text,location_city_text,is_active,created_at) VALUES (1,'Gulistan','Mirzaei',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NONE',0,0,NULL,NULL,NULL,NULL,NULL,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO contacts (id,first_name,last_name,email_primary,email_secondary,company,website,company_linkedin,imdb,facebook,instagram,linkedin,wikipedia,biography,priority,seen_film,doc_branch_member,location_country,location_state,location_city,location_state_text,location_city_text,is_active,created_at) VALUES (2,'Deborah','Shaffer','deboshaffer@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'HIGH',0,1,NULL,NULL,NULL,NULL,NULL,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO contacts (id,first_name,last_name,email_primary,email_secondary,company,website,company_linkedin,imdb,facebook,instagram,linkedin,wikipedia,biography,priority,seen_film,doc_branch_member,location_country,location_state,location_city,location_state_text,location_city_text,is_active,created_at) VALUES (3,'Brett','Story',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NONE',0,1,NULL,NULL,NULL,NULL,NULL,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO contacts (id,first_name,last_name,email_primary,email_secondary,company,website,company_linkedin,imdb,facebook,instagram,linkedin,wikipedia,biography,priority,seen_film,doc_branch_member,location_country,location_state,location_city,location_state_text,location_city_text,is_active,created_at) VALUES (4,'Gerardine','Wurzburg',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NONE',0,0,'US','DC',NULL,NULL,NULL,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO contacts (id,first_name,last_name,email_primary,email_secondary,company,website,company_linkedin,imdb,facebook,instagram,linkedin,wikipedia,biography,priority,seen_film,doc_branch_member,location_country,location_state,location_city,location_state_text,location_city_text,is_active,created_at) VALUES (5,'Alexandra','Garcia','alexandra.garcia@nytimes.com',NULL,'NY Times',NULL,'https://www.linkedin.com/company/the-new-york-times/','https://pro.imdb.com/name/nm9286635/',NULL,'https://www.instagram.com/garcia_alexandra/?hl=en','https://www.linkedin.com/in/garciaalexandra/',NULL,NULL,'NONE',0,1,NULL,NULL,NULL,NULL,NULL,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO contacts (id,first_name,last_name,email_primary,email_secondary,company,website,company_linkedin,imdb,facebook,instagram,linkedin,wikipedia,biography,priority,seen_film,doc_branch_member,location_country,location_state,location_city,location_state_text,location_city_text,is_active,created_at) VALUES (6,'Alex','Gibney','pag@jigsawprods.com','info@jigsawprods.com','Jigsaw Productions',NULL,'https://www.linkedin.com/company/jigsaw-productions','https://pro.imdb.com/name/nm0316795/',NULL,'https://www.instagram.com/alexgibneyfilm/?hl=en',NULL,NULL,NULL,'HIGH',0,1,NULL,NULL,NULL,NULL,NULL,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO contacts (id,first_name,last_name,email_primary,email_secondary,company,website,company_linkedin,imdb,facebook,instagram,linkedin,wikipedia,biography,priority,seen_film,doc_branch_member,location_country,location_state,location_city,location_state_text,location_city_text,is_active,created_at) VALUES (7,'Donald','Young',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'HIGH',0,0,NULL,NULL,NULL,NULL,NULL,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO contacts (id,first_name,last_name,email_primary,email_secondary,company,website,company_linkedin,imdb,facebook,instagram,linkedin,wikipedia,biography,priority,seen_film,doc_branch_member,location_country,location_state,location_city,location_state_text,location_city_text,is_active,created_at) VALUES (8,'Greg','Barker',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NONE',0,0,NULL,NULL,NULL,NULL,NULL,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO contacts (id,first_name,last_name,email_primary,email_secondary,company,website,company_linkedin,imdb,facebook,instagram,linkedin,wikipedia,biography,priority,seen_film,doc_branch_member,location_country,location_state,location_city,location_state_text,location_city_text,is_active,created_at) VALUES (9,'Flavia','De Souza','flaviadesouza@me.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NONE',0,1,NULL,NULL,NULL,NULL,NULL,1,CAST(strftime('%s','now') AS INTEGER) * 1000);
INSERT INTO contacts (id,first_name,last_name,email_primary,email_secondary,company,website,company_linkedin,imdb,facebook,instagram,linkedin,wikipedia,biography,priority,seen_film,doc_branch_member,location_country,location_state,location_city,location_state_text,location_city_text,is_active,created_at) VALUES (10,'Erich','Roland',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NONE',0,0,'US','DC',NULL,NULL,NULL,1,CAST(strftime('%s','now') AS INTEGER) * 1000);

INSERT OR IGNORE INTO contact_assignments (contact_id, user_id) VALUES (2, 3);
INSERT OR IGNORE INTO contact_assignments (contact_id, user_id) VALUES (6, 3);
INSERT OR IGNORE INTO contact_assignments (contact_id, user_id) VALUES (7, 2);
INSERT OR IGNORE INTO contact_assignments (contact_id, user_id) VALUES (9, 3);
