-- US locations only for clean.csv import
DELETE FROM cities;
DELETE FROM states; 
DELETE FROM countries;

-- US country
INSERT INTO countries (code, name) VALUES ('US', 'United States');

-- US states from clean.csv
INSERT INTO states (code, name, country_code) VALUES 
('NY', 'New York', 'US'),
('CA', 'California', 'US'),
('DC', 'District of Columbia', 'US'),
('PA', 'Pennsylvania', 'US'),
('IL', 'Illinois', 'US'),
('LA', 'Louisiana', 'US'),
('MA', 'Massachusetts', 'US'),
('TX', 'Texas', 'US'),
('FL', 'Florida', 'US'),
('WA', 'Washington', 'US'),
('OR', 'Oregon', 'US'),
('CO', 'Colorado', 'US'),
('GA', 'Georgia', 'US'),
('NC', 'North Carolina', 'US'),
('VA', 'Virginia', 'US'),
('MD', 'Maryland', 'US'),
('NJ', 'New Jersey', 'US'),
('CT', 'Connecticut', 'US'),
('VT', 'Vermont', 'US'),
('NH', 'New Hampshire', 'US'),
('ME', 'Maine', 'US'),
('RI', 'Rhode Island', 'US'),
('DE', 'Delaware', 'US'),
('WV', 'West Virginia', 'US'),
('KY', 'Kentucky', 'US'),
('TN', 'Tennessee', 'US'),
('SC', 'South Carolina', 'US'),
('AL', 'Alabama', 'US'),
('MS', 'Mississippi', 'US'),
('AR', 'Arkansas', 'US'),
('OK', 'Oklahoma', 'US'),
('KS', 'Kansas', 'US'),
('NE', 'Nebraska', 'US'),
('SD', 'South Dakota', 'US'),
('ND', 'North Dakota', 'US'),
('MT', 'Montana', 'US'),
('WY', 'Wyoming', 'US'),
('ID', 'Idaho', 'US'),
('UT', 'Utah', 'US'),
('AZ', 'Arizona', 'US'),
('NV', 'Nevada', 'US'),
('NM', 'New Mexico', 'US'),
('AK', 'Alaska', 'US'),
('HI', 'Hawaii', 'US'),
('MO', 'Missouri', 'US'),
('IA', 'Iowa', 'US'),
('MN', 'Minnesota', 'US'),
('WI', 'Wisconsin', 'US'),
('MI', 'Michigan', 'US'),
('IN', 'Indiana', 'US'),
('OH', 'Ohio', 'US');

-- Major US cities from clean.csv
INSERT INTO cities (city, city_ascii, state_code) VALUES
('new york', 'NY'),
('los angeles', 'CA'),
('brooklyn', 'NY'),
('washington', 'DC'),
('philadelphia', 'PA'),
('chicago', 'IL'),
('boston', 'MA'),
('new orleans', 'LA'),
('san francisco', 'CA'),
('seattle', 'WA'),
('portland', 'OR'),
('denver', 'CO'),
('atlanta', 'GA'),
('miami', 'FL'),
('houston', 'TX'),
('dallas', 'TX'),
('austin', 'TX'),
('san diego', 'CA'),
('oakland', 'CA'),
('berkeley', 'CA'),
('pasadena', 'CA'),
('santa monica', 'CA'),
('beverly hills', 'CA'),
('manhattan', 'NY'),
('queens', 'NY'),
('bronx', 'NY'),
('staten island', 'NY'),
('long island', 'NY'),
('westchester', 'NY'),
('albany', 'NY'),
('buffalo', 'NY'),
('rochester', 'NY'),
('syracuse', 'NY'),
('ithaca', 'NY'),
('pittsburgh', 'PA'),
('harrisburg', 'PA'),
('allentown', 'PA'),
('scranton', 'PA'),
('erie', 'PA'),
('reading', 'PA'),
('york', 'PA'),
('lancaster', 'PA'),
('bethlehem', 'PA'),
('wilkes barre', 'PA'),
('chester', 'PA'),
('upper darby', 'PA'),
('norristown', 'PA'),
('chester', 'PA'),
('camden', 'NJ'),
('newark', 'NJ'),
('jersey city', 'NJ'),
('paterson', 'NJ'),
('elizabeth', 'NJ'),
('edison', 'NJ'),
('woodbridge', 'NJ'),
('hamilton', 'NJ'),
('trenton', 'NJ'),
('atlantic city', 'NJ'),
('bridgeport', 'CT'),
('new haven', 'CT'),
('hartford', 'CT'),
('stamford', 'CT'),
('waterbury', 'CT'),
('norwalk', 'CT'),
('danbury', 'CT'),
('new britain', 'CT'),
('west hartford', 'CT'),
('greenwich', 'CT'),
('baltimore', 'MD'),
('frederick', 'MD'),
('rockville', 'MD'),
('gaithersburg', 'MD'),
('bowie', 'MD'),
('hagerstown', 'MD'),
('annapolis', 'MD'),
('college park', 'MD'),
('salisbury', 'MD'),
('cumberland', 'MD'),
('richmond', 'VA'),
('virginia beach', 'VA'),
('norfolk', 'VA'),
('chesapeake', 'VA'),
('newport news', 'VA'),
('hampton', 'VA'),
('alexandria', 'VA'),
('portsmouth', 'VA'),
('suffolk', 'VA'),
('roanoke', 'VA'),
('lynchburg', 'VA'),
('harrisonburg', 'VA'),
('leesburg', 'VA'),
('manassas', 'VA'),
('petersburg', 'VA'),
('fredericksburg', 'VA'),
('winchester', 'VA'),
('salem', 'VA'),
('staunton', 'VA'),
('waynesboro', 'VA'),
('charlottesville', 'VA'),
('danville', 'VA'),
('martinsville', 'VA'),
('galax', 'VA'),
('fairfax', 'VA'),
('falls church', 'VA'),
('arlington', 'VA');
